import type { TourStep } from './guided-tour';

/** Self-guided walkthrough of every togglable control. Hardcoded so it is complete and instant. */
export const FULL_TOUR_STEPS: TourStep[] = [
  {
    id: 'welcome',
    title: 'Guided learning',
    body: 'This walkthrough introduces the chip, design, and learning controls in Qubit Studio. Use Next and Back at your own pace. You can Exit anytime.\nThe 3D chip is a teaching schematic of a transmon qubit — a superconducting circuit that stores a $0$ or a $1$. Numbers at the bottom come from a solver, not from this drawing.',
    target: 'brand',
  },
  {
    id: 'myla',
    title: 'Myla',
    body: 'Outside this tour, select chip parts or metrics and open Ask AI about selection. Local teaching notes and an explicit Ask Gemini action explain the completed evidence.\nDuring the tour, Myla stays quiet so these cards are not fighting each other.',
    target: 'brand',
  },
  {
    id: 'status',
    title: 'Solver status',
    body: 'This badge is the link to the calculation service. Live result means $f_{01}$ and $\\alpha$ are real solver outputs.\nUpdating means you changed a slider and a newer solve is in flight. Calculation failed means the current solve is unavailable.',
    target: 'status',
  },
  {
    id: 'presets',
    title: 'Demo presets',
    body: 'These jump $E_J$, $E_C$, $n_g$, and $\\mathrm{ncut}$ to canned teaching points: a balanced default, the scqubits textbook point, a charge-quiet transmon, and a more anharmonic (noisier) chip.\nThey are not process recipes. Try one after the tour if you want a different starting chip.',
    target: 'presets',
  },
  {
    id: 'export',
    title: 'Export report',
    body: 'Downloads a JSON snapshot: parameters, goals, the last solver result, and any pinned baseline.\nUse it for lab notes. It is not a foundry file.',
    target: 'export',
  },
  {
    id: 'reset-params',
    title: 'Reset parameters',
    body: 'Puts $E_J$, $E_C$, $n_g$, and $\\mathrm{ncut}$ back to the model defaults. Materials, camera, and goals stay as they are.\nHandy after you have dragged sliders a long way from home.',
    target: 'reset-params',
  },
  {
    id: 'save-design',
    title: 'Save design',
    body: 'Stores the current $E_J$, $E_C$, $n_g$, goals, and materials in this browser (up to 10).\nRestore or the Saved menu brings one back. Nothing is uploaded.',
    target: 'save-design',
  },
  {
    id: 'history',
    title: 'Saved history',
    body: 'A list of designs you saved here. Click one to restore its parameters and material pair.\nCopy link writes the same state into the URL so a teammate can open it.',
    target: 'history',
  },
  {
    id: 'geometry',
    title: 'Shape the junction and capacitor',
    body: 'On Edit chip, this converts area into $E_J$ and $E_C$ with two stated teaching assumptions, then previews the 3D pads and junction.\nIt is not a mask layout. Apply writes the estimated energies onto the live chip.',
    target: 'geometry',
    tab: 'edit',
  },
  {
    id: 'parts',
    title: 'Parts list',
    body: 'This column is the bill of materials for the drawing. Click a name to select it on the chip and open its slider on the right.\nOnly three parts change the math: the junction ($E_J$), the pads ($E_C$), and the gate ($n_g$).',
    target: 'parts-panel',
  },
  {
    id: 'part-junction',
    title: 'Josephson junction',
    body: 'The small nonlinear element. Its energy $E_J=\\hbar I_c/(2e)$ is set in a lab by junction area and oxide thickness.\nRaising $E_J$ increases the operating frequency $f_{01}$ and the ratio $E_J/E_C$, which hides the qubit from stray charge.',
    target: 'part-junction',
    tab: 'edit',
    part: 'junction',
  },
  {
    id: 'part-capacitor',
    title: 'Shunt capacitor pads',
    body: 'Two large islands across the junction. They set the charging energy $E_C=e^2/(2C_\\Sigma)$.\nBigger pads $\\Rightarrow$ more $C$ $\\Rightarrow$ smaller $E_C$: quieter versus charge, but weaker anharmonicity $\\alpha$.',
    target: 'part-capacitor',
    tab: 'edit',
    part: 'capacitor',
  },
  {
    id: 'part-gate',
    title: 'Charge gate line',
    body: 'Applies an offset charge $n_g$ (in Cooper pairs) to the island. Sweeping $0\\to 1$ traces how $f_{01}$ would wander if the electrostatic environment drifted.\nOn a transmon that curve is almost flat. On a charge qubit it would swing hard.',
    target: 'part-gate',
    tab: 'edit',
    part: 'gate',
  },
  {
    id: 'part-ground',
    title: 'Ground plane',
    body: 'Surrounding metal drawn so the chip looks like a chip. It is not an input to the isolated-transmon Hamiltonian.\nSize, slots, and color cannot move $f_{01}$ or $\\alpha$ in this model.',
    target: 'part-ground',
    tab: 'edit',
    part: 'ground',
  },
  {
    id: 'part-substrate',
    title: 'Substrate',
    body: 'The wafer under the metal. In a real process $\\varepsilon_r$ would set capacitance; here thickness and color are illustrative.\nThe Materials tab can recolor it. That is not a capacitance extract.',
    target: 'part-substrate',
    tab: 'edit',
    part: 'substrate',
  },
  {
    id: 'hide-part',
    title: 'Show / hide',
    body: 'The eye on each row hides that part in the 3D and schematic views so you can see what sits underneath.\nHiding is view-only. The solver still uses $E_J$, $E_C$, and $n_g$ even if the junction is invisible.',
    target: 'hide-junction',
    tab: 'edit',
    part: 'junction',
  },
  {
    id: 'view-3d',
    title: '3D view',
    body: 'The default camera. Drag to orbit, right-drag to pan, scroll to zoom. Click a gold or grey piece to select it.\nThis is a schematic, not a GDS mask and not to scale.',
    target: 'view-3d',
    view: '3d',
  },
  {
    id: 'view-schematic',
    title: 'Layout / circuit view',
    body: 'A 2-D circuit drawing of the same transmon: junction, pads, gate, ground. Clickable the same way as the 3D chip.\nUse it when the 3D view feels busy.',
    target: 'view-schematic',
    view: 'schematic',
  },
  {
    id: 'view-split',
    title: 'Split view',
    body: 'Shows 3D and schematic together. Same selection, same hidden parts, same explode amount.\nNothing extra is computed; it is only two cameras on one model.',
    target: 'view-split',
    view: 'split',
  },
  {
    id: 'reset-view',
    title: 'Reset view',
    body: 'Returns the 3D camera to its starting orbit. Does not change $E_J$, $E_C$, or any result.\nUse it after you have zoomed into the junction and gotten lost.',
    target: 'reset-view',
    view: '3d',
  },
  {
    id: 'assembly',
    title: 'Assembly / explode',
    body: 'Pulls the parts apart so you can see the junction between the pads. The label will say exploded (view only).\nThe Hamiltonian does not care. Collapse it before you treat the picture as a chip.',
    target: 'assembly',
    view: '3d',
  },
  {
    id: 'legend',
    title: 'Material legend',
    body: 'Room-light colors for the current top metal and base wafer so you can tell films apart.\nChanging materials on the right recolors this immediately. Color is not kinetic inductance or $T_1$.',
    target: 'legend',
    view: '3d',
  },
  {
    id: 'tab-edit',
    title: 'Edit chip',
    body: 'This inspector tab is where you type or drag the three Hamiltonian inputs.\nPick a part in the tree (or on the chip) and its slider appears here.',
    target: 'tab-edit',
    tab: 'edit',
    part: 'junction',
  },
  {
    id: 'slider-ej',
    title: 'Junction energy $E_J$',
    body: 'Drag this to change tunnelling. $E_J$ and $E_C$ are independent inputs; $f_{01}$ is an output of the solver.\nThe exact box next to the slider rejects numbers outside the model range instead of silently clamping them. Reset on the right returns only this slider.',
    target: 'field-ej',
    tab: 'edit',
    part: 'junction',
  },
  {
    id: 'tech-detail',
    title: 'Technical detail',
    body: 'Opens the symbol, allowed range, and a one-line reminder that $f_{01}$ is computed, not typed.\nLeave it closed until you want the formula; the slider already does the physics.',
    target: 'tech-detail',
    tab: 'edit',
    part: 'junction',
    openDetails: '[data-tour="tech-detail"]',
  },
  {
    id: 'slider-ec',
    title: 'Charging energy $E_C$',
    body: 'This is the pad slider. Smaller $E_C$ (bigger pads) protects against charge noise but shrinks $|\\alpha|\\approx E_C$, so $|1\\rangle$ is harder to address alone.\nThat is the central transmon tradeoff.',
    target: 'field-ec',
    tab: 'edit',
    part: 'capacitor',
  },
  {
    id: 'slider-ng',
    title: 'Offset charge $n_g$',
    body: 'A diagnostic, not a performance knob. Sweep $0\\to 1$ and watch the charge-response chart in Results.\nIf $f_{01}$ barely moves, you are in the transmon window. If it swings, raise $E_J/E_C$.',
    target: 'field-ng',
    tab: 'edit',
    part: 'gate',
  },
  {
    id: 'ncut',
    title: 'Solver cutoff $\\mathrm{ncut}$',
    body: 'How many charge states the numerical diagonalization keeps. It is not a lithography step.\nDefault $30$ is enough for a typical transmon. Raise it only if $E_J/E_C$ is huge and the levels look unstable.',
    target: 'ncut',
    tab: 'edit',
    openDetails: '[data-tour="ncut"]',
  },
  {
    id: 'tab-goal',
    title: 'Try a goal',
    body: 'Instead of dragging $E_J$ by hand, you state a target frequency (and optional rules). The app searches a grid of designs.\nA pass means “this grid point satisfies your cuts,” not “this is the chip you should fabricate.”',
    target: 'tab-goal',
    tab: 'experiment',
  },
  {
    id: 'goal-freq',
    title: 'Target operating frequency',
    body: 'The $f_{01}$ you wish the search to hit, usually $4$–$6.5\\,\\mathrm{GHz}$ in a real fridge.\n$5\\,\\mathrm{GHz}$ is a friendly demo starting point.',
    target: 'goal-freq',
    tab: 'experiment',
  },
  {
    id: 'goal-rules',
    title: 'What counts as a good design',
    body: 'Three extra cuts: how close $f_{01}$ must be to target, a minimum $|\\alpha|$ so you can address $|1\\rangle$, and a maximum charge dispersion so stray $n_g$ stays quiet.\nTighter cuts mean fewer grid points survive.',
    target: 'goal-rules',
    tab: 'experiment',
    openDetails: '[data-tour="goal-rules"]',
  },
  {
    id: 'goal-tol',
    title: 'Allowed frequency error',
    body: 'Search keeps designs whose $f_{01}$ is within this window of your target.\nMake it small if you care about sitting on a specific control frequency; make it larger if you just want “somewhere in band.”',
    target: 'goal-tol',
    tab: 'experiment',
    openDetails: '[data-tour="goal-rules"]',
  },
  {
    id: 'goal-alpha',
    title: 'Minimum level separation',
    body: 'Search rejects chips whose $|\\alpha|$ is below this. Higher is easier to control, harder to combine with a huge $E_J/E_C$.\nTypical transmons live around $200$–$350\\,\\mathrm{MHz}$.',
    target: 'goal-alpha',
    tab: 'experiment',
    openDetails: '[data-tour="goal-rules"]',
  },
  {
    id: 'goal-disp',
    title: 'Maximum charge sensitivity',
    body: 'Search rejects chips whose charge dispersion is louder than this. Lower is quieter versus stray $n_g$.\nA transmon’s exponential protection is why this cut is even possible.',
    target: 'goal-disp',
    tab: 'experiment',
    openDetails: '[data-tour="goal-rules"]',
  },
  {
    id: 'mat-priority',
    title: 'Material ranking priority',
    body: 'After a passing electrical point is found, stacks from a measured catalog are ranked. Left prefers a simpler recorded process; right prefers lower published resonator loss.\nThis is a heuristic on public data, not a foundry quote.',
    target: 'mat-priority',
    tab: 'experiment',
  },
  {
    id: 'mat-base',
    title: 'Required chip base',
    body: 'Optionally restrict the ranked stack to silicon, sapphire, or any measured substrate in the catalog.\nThe electrical $E_J,E_C$ search does not depend on this; only the material suggestion does.',
    target: 'mat-base',
    tab: 'experiment',
  },
  {
    id: 'search-run',
    title: 'Find variables + materials',
    body: 'Runs the grid search (201 points in the default demo) and, if something passes, shows $E_J$, $E_C$, and a suggested metal/substrate pair.\nUse variables + materials writes those numbers onto the live chip. It still does not predict $T_1$.',
    target: 'search-run',
    tab: 'experiment',
  },
  {
    id: 'stress',
    title: 'Robustness test',
    body: 'Wiggles $E_J$ and $E_C$ by a few percent in nine combinations to mimic junction-area and pad-size scatter.\nWatch whether $f_{01}$ and dispersion stay inside your goals. This is a sensitivity test, not a yield model.',
    target: 'stress',
    tab: 'experiment',
    openDetails: '[data-tour="stress"]',
  },
  {
    id: 'stress-var',
    title: 'Possible variation',
    body: 'How hard to shove $E_J$ and $E_C$ in that robustness grid, in percent.\nA few percent is a fair teaching stand-in for lithography scatter; $20\\%$ is a stress test, not a realistic process spec.',
    target: 'stress-var',
    tab: 'experiment',
    openDetails: '[data-tour="stress"]',
  },
  {
    id: 'tunable',
    title: 'Flux-tunable chip',
    body: 'Replaces one junction with a SQUID so magnetic flux $\\Phi/\\Phi_0$ can change the effective $E_J$.\nThis is a separate Hamiltonian. It does not rewrite the isolated transmon on the 3D chip.',
    target: 'tunable',
    tab: 'experiment',
    openDetails: '[data-tour="tunable"]',
  },
  {
    id: 'flux',
    title: 'Magnetic flux',
    body: '$\\Phi/\\Phi_0$ through the SQUID loop. At half-flux the effective $E_J$ is smallest (for a symmetric SQUID), so $f_{01}$ drops.\nAsymmetry between the two junctions keeps a little $E_J$ even at half flux so the qubit does not go dark.',
    target: 'flux',
    tab: 'experiment',
    openDetails: '[data-tour="tunable"]',
  },
  {
    id: 'asymmetry',
    title: 'Junction asymmetry',
    body: 'How unequal the two SQUID junctions are. Real devices are never perfectly matched.\nA few tens of percent is common. This slider only affects the flux-tunable toy model.',
    target: 'asymmetry',
    tab: 'experiment',
    openDetails: '[data-tour="tunable"]',
  },
  {
    id: 'tab-materials',
    title: 'Materials tab',
    body: 'A sandbox over a verified catalog of real films and wafers. You may pair any two, even the same material twice.\nThe 3D colors update immediately. Electrical $E_J,E_C$ only change if you run a scenario below.',
    target: 'tab-materials',
    tab: 'materials',
  },
  {
    id: 'top-mat',
    title: 'Top material',
    body: 'The metal film (Al, Nb, Ta, TiN, …). Color is a room-light stand-in so you can tell films apart.\nIf the catalog has a resonator-loss record for this pair, you will see published $\\delta_{LP}$ — still not qubit $T_1$.',
    target: 'top-mat',
    tab: 'materials',
  },
  {
    id: 'base-mat',
    title: 'Base material',
    body: 'The wafer (Si, sapphire, …). Same rules: real names, no invented loss if the pair is missing from the dataset.\nSome exotic pairs (for example Pb on InAs) are allowed and labelled as “no EJ/EC record,” not as a topological qubit.',
    target: 'base-mat',
    tab: 'materials',
  },
  {
    id: 'junction-fx',
    title: 'Junction effect',
    body: 'A teaching scale: “what if $I_c$ (hence $E_J$) moved by this percent because of the metal choice?”\nIt is not extracted from $\\Delta$ or $T_c$. Compare scenario then Apply if you want those $E_J,E_C$ on the live chip.',
    target: 'junction-fx',
    tab: 'materials',
  },
  {
    id: 'cap-fx',
    title: 'Total capacitance',
    body: 'Same idea for $C_\\Sigma$ (hence $E_C$), as if the dielectric or pad participation changed.\nClear effects puts both factors back to $0\\%$ without touching the 3D colors.',
    target: 'cap-fx',
    tab: 'materials',
  },
  {
    id: 'compare',
    title: 'Compare scenario',
    body: 'Re-solves the transmon at the scaled $E_J$ and $E_C$ and shows $f_{01}$, $\\alpha$, and dispersion before $\\to$ after.\nApply modified EJ and EC writes the scaled inputs onto the chip. Clear effects only resets the two percent sliders.',
    target: 'compare',
    tab: 'materials',
  },
  {
    id: 'verdict',
    title: 'Goal verdict',
    body: 'A live pass/fail against the targets you set in Try a goal: frequency window, $|\\alpha|$, charge dispersion.\nIt updates whenever the solver returns. Click it and Myla will interpret the misses.',
    target: 'verdict',
  },
  {
    id: 'metric-f01',
    title: 'Operating frequency $f_{01}$',
    body: 'The microwave tone that flips $|0\\rangle\\to|1\\rangle$. Typical transmon labs sit at $4$–$6.5\\,\\mathrm{GHz}$.\nYou never type this. Change $E_J$ or $E_C$ and the solver computes it. Click the number anytime for Myla.',
    target: 'metric-f01',
  },
  {
    id: 'metric-f12',
    title: 'Next rung $f_{12}$',
    body: '$f_{12}$ is $|1\\rangle\\to|2\\rangle$, lower than $f_{01}$ by $|\\alpha|$. That gap is why a drive at $f_{01}$ can miss leakage.\nIf $|\\alpha|$ is tiny, a short pulse is spectrally wide enough to nibble $|2\\rangle$.',
    target: 'metric-f12',
  },
  {
    id: 'metric-alpha',
    title: 'Level separation $\\alpha$',
    body: 'How uneven the energy ladder is. For a transmon $\\alpha\\approx -E_C$, usually $-200$ to $-350\\,\\mathrm{MHz}$.\nThat gap is why a pulse can hit $|1\\rangle$ without leaking into $|2\\rangle$. An LC oscillator has $\\alpha=0$.',
    target: 'metric-alpha',
  },
  {
    id: 'metric-disp',
    title: 'Charge sensitivity',
    body: 'How much $f_{01}$ would wander if $n_g$ drifted by half a Cooper pair. Transmons make this tiny on purpose.\nA value below the reporting floor is not zero — just smaller than this solver will quote.',
    target: 'metric-disp',
  },
  {
    id: 'tech-results',
    title: 'Technical details and charts',
    body: 'Opens the derived quantities ($E_J/E_C$, signed $\\alpha$, $I_c$, $C_\\Sigma$) plus the two plots.\nKeep it closed for a clean dashboard; open it when you want the ladder and the charge curve.',
    target: 'tech-results',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'baseline',
    title: 'Save baseline',
    body: 'Freezes the current completed result. Later numbers show a delta against that snapshot.\nA rise or fall is not automatically better — it depends on the frequency and charge-noise you wanted. Clear drops the pin.',
    target: 'baseline',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'metric-ratio',
    title: '$E_J/E_C$ ratio',
    body: 'The derived transmon-ness. $\\ge 20$ is the usual floor; $30$–$80$ is common in papers.\nYou cannot type it. It is $E_J$ divided by $E_C$. Below $\\sim 20$ you are walking back toward a charge qubit.',
    target: 'metric-ratio',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'metric-ic',
    title: 'Critical current',
    body: 'Derived from $E_J=\\hbar I_c/(2e)$, quoted in nA. In a cleanroom you would set this with junction area.\nHere it is a readout of the $E_J$ you already chose, not a second independent knob.',
    target: 'metric-junction',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'metric-c',
    title: 'Total capacitance',
    body: 'Derived from $E_C=e^2/(2C_\\Sigma)$, quoted in fF. Bigger pads, more $C$, smaller $E_C$.\nAgain a readout, not a geometry extractor.',
    target: 'metric-capacitor',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'chart-levels',
    title: 'Energy-level chart',
    body: 'Rungs of the oscillator relative to $|0\\rangle$. The blue gap is $f_{01}$; the next gap is $f_{12}=f_{01}+\\alpha$.\nDashed lines appear once you save a baseline. Click the chart for Myla.',
    target: 'chart-levels',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'drive-cartoon',
    title: 'Drive vs leakage',
    body: 'A cartoon of a pulse sitting on $f_{01}$ and missing $f_{12}$. If $|\\alpha|$ is small, the pulse is drawn wider and the warning turns on.\nIt is a sketch, not a time-domain simulation of a DRAG pulse.',
    target: 'drive-cartoon',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'charge-peer',
    title: 'Same $E_C$, charge qubit',
    body: 'An extra solver run at $E_J=E_C$ (ratio 1) with the same charging energy. Watch how huge the charge wiggle becomes.\nThat contrast is why Koch et al. pushed $E_J/E_C$ up. Not a second fabricated chip.',
    target: 'charge-peer',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'chart-charge',
    title: 'Charge-response chart',
    body: '$f_{01}$ versus offset charge $n_g$, plotted as a shift from $n_g=0$. Flat means protected; wiggly means a charge qubit.\nThis is the picture corresponding to the charge-sensitivity metric.',
    target: 'chart-charge',
    openDetails: '[data-tour="tech-results"]',
  },
  {
    id: 'finish',
    title: 'You can drive it now',
    body: 'That was every togglable control. Exit returns you to free exploration; Myla will speak again when you click.\nRemember: $E_J$ and $E_C$ are inputs, $f_{01}$ and $\\alpha$ are outputs, and this model does not predict $T_1$.',
    target: 'brand',
    tab: 'edit',
    view: '3d',
    part: null,
  },
];
